import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { mantineHtmlProps } from "@mantine/core"; //If your application has server side rendering, add ColorSchemeScript to the <head /> of your application and spread mantineHtmlProps on the <html /> element to avoid seeing a hydration warning:
import { HeaderSimple } from "@/components/HeaderSimple";
import { ModalsProvider } from "@mantine/modals";
import { MantineProvider } from "@mantine/core";

import "@mantine/core/styles.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider>
          {/* header that is rendered client side so it can use hooks */}
          <HeaderSimple />
          {/* this is where all the pages get rendered */}
          <ModalsProvider>{children}</ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
